package cz.cvut.fel.omo.enums;

public enum MaterialType {

    // Car components
    AUDI_ELECTRONICS, AUDI_ENGINE, AUDI_HOOD, AUDI_WHEEL,
    SKODA_ELECTRONICS, SKODA_ENGINE, SKODA_HOOD, SKODA_WHEEL,
    MERCEDES_ELECTRONICS, MERCEDES_ENGINE, MERCEDES_HOOD, MERCEDES_WHEEL,
    BULLET_TIME_ELECTRONICS, BULLET_TIME_ENGINE, BULLET_TIME_HOOD, BULLET_TIME_WHEEL,
    // Tires
    TIRE_18_IN, TIRE_20_IN, TIRE_22_IN, TIRE_30_IN,
    // Paint
    RED_PAINT, BLUE_PAINT, BLACK_PAINT, WHITE_PAINT
}
